services:
  app:
    image: itacademy/airports:1.3
    build: .
    ports:
      - "80:8080"
  db:
    image: itacademy/postgres:1.1
    build: postgres
    volumes:
      - "C:/dockerPostgresTest:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    networks:
      - test
networks:
  test:
    name: test